version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - dsw:/data/db

  express:
    image: mongo-express
    container_name: express
    restart: always
    ports:
      - 8081:8081

volumes:
  dsw:
