spring:
  data:
    mongodb:
      host: localhost
      database: demo
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: trabalhodegrupoti@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
